[package]
name = "dfu-cross-usb"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
futures = "0.3.31"
usb = "0.3"
wasm-bindgen-futures = "0.4"
cross_usb = { git = "https://github.com/G2-Games/cross-usb.git" }
dfu-core = { version = "0.7.0", features = ["std", "async"] }
